apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:ihavasu/k8s-deploy
    targetRevision: main
    path: overlays/gcp-ihavasu-chatbot-challenge-dev/env0-uswe1a-cc/chatbot
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
