apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: chatbot

resources:
- namespace.yaml
- ../../../../base/cluster-addons/ingress-nginx
- service.yaml
- ingress.yaml
- datadog-metric.yaml
- deployment.yaml
- hpa.yaml
