apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources: 
- ../../../../../base/cluster-addons/traefik
- service.yaml

patchesStrategicMerge:
- serviceaccount-patch.yaml

patchesJson6902:
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: traefik
    version: v1
