apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../../base/cluster-addons/argocd

patchesStrategicMerge:
- argocd-cm.yaml
- argocd-rbac-cm.yaml

patchesJson6902:
- path: deployment-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1
