apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ default "https://kubernetes.default.svc" .Values.spec.destination.server }}
  project: default
  source:
    path: {{ .Values.spec.source.path }}/argocd/traefik
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
