apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  template:
    metadata:
      annotations:
        ad.datadoghq.com/controller.check_names: '["nginx","nginx_ingress_controller"]'
        ad.datadoghq.com/controller.init_configs: '[{},{}]'
        ad.datadoghq.com/controller.instances: '[{"nginx_status_url": "http://%%host%%:18080/nginx_status"},{"prometheus_url": "http://%%host%%:10254/metrics"}]'
        ad.datadoghq.com/controller.logs: '[{"service":"controller","source":"nginx-ingress-controller"}]'
